micronaut:
  application:
    name: desafioPix

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024

datasources:
  default:
    url: jdbc:postgresql://localhost:5433/pix
    driverClassName: org.postgresql.Driver
    username: admin
    password: admin
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

clients:
  url:
    erp-itau: http://localhost:9091/api/v1/
    bcb: http://localhost:8082/api/v1/pix/keys


